name: llama-2-13b-chat/baseline
dataset: data/paper-dataset-1-12.json
llama_2_single_kdma_adm:
  baseline: true
  device: cuda:0
  hf_model: meta-llama/Llama-2-13b-chat-hf
  n_negative_samples: 0
  n_positive_samples: 1
  precision: half
  shuffle: false
  temperature: 0.7
target_kdma_values: null
