name: falcon-7b-instruct/align/low
dataset: data/paper-dataset-1-12.json
llama_2_single_kdma_adm:
  baseline: false
  chat_template: falcon-instruct.jinja
  device: cuda:0
  hf_model: tiiuae/falcon-7b-instruct
  n_negative_samples: 0
  n_positive_samples: 1
  precision: half
  shuffle: false
  temperature: 0.7
target_kdma_values:
  basic_knowledge: 0
  continuation_of_care: 0
  fairness: 0
  moral_deservingness: 0
  protocol_focus: 0
  risk_aversion: 0
  time_pressure: 0
  utilitarianism: 0
