name: mistral-7b-instruct/baseline
dataset: data/paper-dataset-1-12.json
llama_2_single_kdma_adm:
  baseline: true
  device: cuda:0
  hf_model: mistralai/Mistral-7B-Instruct-v0.1
  n_negative_samples: 0
  n_positive_samples: 1
  precision: half
  shuffle: false
  temperature: 0.7
target_kdma_values: null
