name: llama-2-13b-chat/align/high
dataset: data/paper-dataset-1-12.json
llama_2_single_kdma_adm:
  baseline: false
  device: cuda:0
  hf_model: meta-llama/Llama-2-13b-chat-hf
  n_negative_samples: 0
  n_positive_samples: 1
  precision: half
  shuffle: false
  temperature: 0.7
target_kdma_values:
  basic_knowledge: 10
  continuation_of_care: 10
  fairness: 10
  moral_deservingness: 10
  protocol_focus: 10
  risk_aversion: 10
  time_pressure: 10
  utilitarianism: 10
