name: paper-dataset-1-12/llama-2-13b-chat/align_self-consistency/high
dataset: data/paper-dataset-1-12.json
llama_2_single_kdma_adm:
  baseline: false
  device: cuda:0
  hf_model: meta-llama/Llama-2-13b-chat-hf
  n_negative_samples: 5
  n_positive_samples: 5
  precision: half
  shuffle: true
  temperature: 0.7
target_kdma_values:
  continuation_of_care: 10
  fairness: 10
  moral_deservingness: 10
  protocol_focus: 10
  risk_aversion: 10
  utilitarianism: 10
