name: paper-dataset-1-12/mistral-7b-instruct/align_self-consistency/low
dataset: data/paper-dataset-1-12.json
llama_2_single_kdma_adm:
  baseline: false
  device: cuda:0
  hf_model: mistralai/Mistral-7B-Instruct-v0.1
  n_negative_samples: 5
  n_positive_samples: 5
  precision: half
  shuffle: true
  temperature: 0.7
target_kdma_values:
  continuation_of_care: 0
  fairness: 0
  moral_deservingness: 0
  protocol_focus: 0
  risk_aversion: 0
  utilitarianism: 0
