name: kaleido-large/no-descriptions/low

dataset: 'data/paper-dataset-1-12.json'

target_kdma_values:
  moral_deservingness: 0
  continuation_of_care: 0
  risk_aversion: 0
  fairness: 0
  protocol_focus: 0
  utilitarianism: 0

kaleido_adm:
  model_name: 'allenai/kaleido-large'
  use_tqdm: False

  distance_fn: 'RelevanceWeightedDistance'
