name: kaleido-large/no-descriptions/high

dataset: 'data/paper-dataset-1-12.json'

target_kdma_values:
  moral_deservingness: 10
  continuation_of_care: 10
  risk_aversion: 10
  fairness: 10
  protocol_focus: 10
  utilitarianism: 10

kaleido_adm:
  model_name: 'allenai/kaleido-large'
  use_tqdm: False

  distance_fn: 'RelevanceWeightedDistance'
